### ISSUE TITLE
Can't Connect to MySQL

### ISSUE THREAD

**Issue by edm00se** [joelkesler/openshift-koken#1]
During the koken initial setup, I get to the "Setup database" page and enter my host (verified from OpenShift) IP, database name, user name, and password and I get the following error:
"Database connection error: No such file or directory"

I verified the environment variables are valid and working correctly; it just seems that koken isn't taking them. Let me know if there's something I can try; I'd love to get this working on OpenShift (thanks for putting the cartridge together).

**Comment by joelkesler** [comment]
I have not had time to look into it currently, but the installer I modified for it /should/ have everything filled in already.

I made the changes here:

https://github.com/joelkesler/openshift-koken/blob/master/.openshift/koken/index.php#L134-L142

You have the mysql cartridge installed for openshift, correct?

**Comment by edm00se** [comment]
Yes I do, along with the Zend cartridge, as you described in the ReadMe.

I'll check out the changed installer and let you know how it goes.

**Comment by joelkesler** [comment]
Another thing you can do is to grab the latest installer from the koken website and modify if with the Openshift enviroment variables like in the link above :)

I just did a diff of the current installer and what i have in the repo and there is quite a bit different

**Comment by edm00se** [comment]
It kept giving me a tough time with the environment variables. I eventually got it to work with the stock (current) koken install php (coincidentally on a stock PHP 5.4 cartridge with MySQL 5.5). Thanks for the suggestion.

The fork I got to work:
https://github.com/edm00se/openshift-koken
